#服务器配置
server:
  port: 8090
  undertow:
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #  redis:
#    ##redis 单机环境配置
#    host: 192.168.7.129
#    port: 6379
#    password: redis_password
#    database: 0
#    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.7.129:3306/wedding?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: mysqlPassword4!
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: oracle.jdbc.OracleDriver
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      # MySql、PostgreSQL、SqlServer校验
      validation-query: select 1
      # Oracle校验
      #validation-query: select 1 from dual
      validation-query-timeout: 2000
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        login-username: blade
        login-password: 1qaz@WSX
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10

# mybatis
mybatis-plus:
  mapper-locations: classpath:com/tx/demo/**/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: org.springblade.**.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_empty
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: 9609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c29609b32aa0fe11ec91e9000c2
  # 令牌过期时间 此处单位/毫秒
  token-validity-in-seconds: 14400000

##knife4j配置
#knife4j:
#  #启用
#  enable: true
#  #基础认证
#  basic:
#    enable: false
#    username: blade
#    password: blade
##  #增强配置
#  setting:
#    enableSwaggerModels: true
#    enableDocumentManage: true
#    enableHost: false
##    enableHostText: http://localhost
#    enableRequestCache: true
#    enableFilterMultipartApis: false
#    enableFilterMultipartApiMethodType: POST
#    language: zh-CN
#    enableFooter: false
#    enableFooterCustom: true
#    footerCustomContent: Copyright ? 2021 BladeX All Rights Reserved


##blade配置
#blade:
#  #token配置
#  token:
#    #是否有状态
#    state: false
#  #redis序列化方式
#  redis:
#    serializer-type: protostuff
#  #接口配置
#  api:
#    #报文加密配置
#    crypto:
#      #启用报文加密配置
#      enabled: false
#      #使用AesUtil.genAesKey()生成
#      aes-key: O2BEeIv399qHQNhD6aGW8R8DEj4bqHXm
#      #使用DesUtil.genDesKey()生成
#      des-key: jMVCBsFGDQr1USHo
#  #jackson配置
#  jackson:
#    #null自动转空值
#    null-to-empty: true
#    #大数字自动转字符串
#    big-num-to-string: true
#    #支持text文本请求,与报文加密同时开启
#    support-text-plain: false
